### ISSUE TITLE
Current wordpress version not working

### ISSUE THREAD

**Issue by pwqw** [themejack/pine#6]
![Nothing Found](https://cloud.githubusercontent.com/assets/4590357/19524052/d55f307a-95f2-11e6-9579-a7a0a4f332f7.png)

..and I have many entries created.

Version 4.6.1

**Comment by rocketpear** [comment]
If this is what you see on the page with "project list" template, it's because you need to install WP Jetpack plugin and then enable the "protfolio" post type (or maybe it's called projects?). All "projects" will then appear as you see in the demo. Regular "Posts" won't appear in this loop, that's why it acts as if there was nothing to show.

I was wondering about this good few days before I figured that out, this requirement is not stated very clearly in the documentation.

**Comment by pwqw** [comment]
Really is no clearly.
Well, thanks so much!

**Comment by anteprimorac** [comment]
@Delltar thank you for resolving this issue.

Documentation will be updated in next release.
